### ISSUE TITLE
Validate compatibility with C* 4.0, 3.0, 2.x

### ISSUE THREAD

**Issue by zegelin** [instaclustr/cassandra-everywhere-strategy#1]
Currently the project has only been tested against 3.11.x (specifically 3.11.6).

This ticket is a placeholder to track the status of testing against alternate C* versions.

**Comment by smiklosovic** [comment]
It is compatible with 4, 3.11 and 3.0 as well as with 2.2 and it is tested via your "test suite" upon every commit in CI.
