### ISSUE TITLE
Error while using everywhere strategy JAR in Apache cassandra

### ISSUE THREAD

**Issue by sandeepmallik** [instaclustr/cassandra-everywhere-strategy#11]
I am using everywhere strategy to add new dc with apache cassandra (3.0.16) to existing cluster DSE 5.0.15. Copied everywhere strategy JAR to $CASSANDRA_HOME/lib

If I change the replication to NetworkTopologyStrategy, it works but if I restart any dse node that node will revert replication to EverywhereStrategy.

Got this error.

cqlsh> select * from dse_system.leases;
**NoHostAvailable:** 

cqlsh> desc keyspace dse_system;
CREATE KEYSPACE dse_system WITH replication = {'class': 'EverywhereStrategy'}  AND durable_writes = true;

How to overcome this?

**Comment by smiklosovic** [comment]
@sandeepmallik this is expected.

Read the documentation please:

_ As a result, if any DSE nodes restart while Cassandra nodes are present in the cluster then schema disagreement will again occur._

You are not supposed to restart anything. This is about starting the second Cassandra dc, migrate and shut down dse dc.

**Comment by sandeepmallik** [comment]
@smiklosovic 

Thanks. As you can see here, I have a single node cassandra cluster (3.0.16) and unable to insert data into table with EverywhereStrategy strategy. Let me know if I am missing anything.

root@instance-3:~/cass3026# ls /root/cass3026/lib/everywhere-strategy-cassandra-4.0-1.0.0.jar 
/root/cass3026/lib/everywhere-strategy-cassandra-4.0-1.0.0.jar

cqlsh> CREATE KEYSPACE example with replication = {'class': 'EverywhereStrategy'};
cqlsh> CREATE TABLE example.demo (a text PRIMARY KEY);

**cqlsh> INSERT INTO example.demo (a) VALUES ('a');
NoHostAvailable:**

root@instance-3:~/cass3026# ./bin/nodetool status
Datacenter: datacenter1
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address    Load       Tokens       Owns (effective)  Host ID                               Rack
UN  127.0.0.1  92.45 KB   256          0.0%              ae77eece-9af3-4af8-8d98-2f12790bda9b  rack1

**Comment by smiklosovic** [comment]
You are using wrong JAR

everywhere-strategy-cassandra-4.0-1.0.0.jar - that is jar for Cassandra version 4.0, but you said you use 3.0.16 so you need to use jar for that.

I see there is only version 4.0.0 among releases in GH and 3.0 is missing. What you need to do is to clone this repository and "mvn clean install" it all and go to cassandra-3.0/target dir and use that jar.

**Comment by sandeepmallik** [comment]
@smiklosovic thanks. It worked. 
I was under impression everywhere-strategy-cassandra-4.0-1.0.0.jar has backward compatibility with 3.0.
